### ISSUE TITLE
android 14  crash

### ISSUE THREAD

**Issue by osbornZ** [SumSubstance/react-native-mobilesdk-module#14]
iOS. work well, but android crash, just in  android 14
  
   ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34

// crash log

Unable to resume activity {com.xxx.client/com.sumsub.sns.presentation.screen.SNSAppActivity}: java.lang.SecurityException: com.xxx.client: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
android.app.ActivityThread.performResumeActivity

`Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.xxx.client/com.sumsub.sns.presentation.screen.SNSAppActivity}: java.lang.SecurityException: com.xxx.client: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5426)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5507)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8913)`

**Comment by alan-cushla** [comment]
@osbornZ I'm getting this also, what was the solution?
